### PR TITLE
Update prestige detection.

### PR DESCRIPTION
**Pull request by relaera**
Added a new dict key for prestige_image as well as updated the prestige image detection data.
A better solution would be to rename the dict keys, but I don't want to change existing data on without updating the API version.

### CODE REVIEW

**Comment by alfg** [comment]
Just curious @relaera, how did you get the prestige level and star mappings? Also, do you know if the prestige borders go beyond 24?

**Comment by Js41637** [comment]
I assume by manually viewing profiles or getting a script to go through as many profiles you can find until you find them all. The hashes are random so there's no way you can figure them out unlike the old ones.

Diamond (or 24) is currently the highest rank/border you can get.

**Comment by relaera** [comment]
@alfg

I modified the script to have the API return the two image links for stars and borders, then threw enough battletags at the API (dumped into a db) and manually checked every distinct hash to map them.

It definitely threw me for a loop that Gold and Plat borders use the same images for stars. My highest level account isn't even Lv 200

**Comment by Js41637** [comment]
Nice job though, I had a similar idea but, I was too lazy to try and do it.

**Comment by alfg** [comment]
@relaera Ah, nice work! Thank you!

**Pull request merged**
